In [1]:
import pandas as pd
import numpy as np

import os

In [2]:
data_dir  = "/lustre/groups/ml01/workspace/ot_perturbation/data/pbmc/similarities"
df= pd.read_csv(os.path.join(data_dir, "df_cytokine_sim.csv"), index_col=0)

In [4]:
df_long = df.stack().reset_index()
df_long.columns = ['Row', 'Column', 'Similarity']
df_long.set_index(['Row', 'Column'], inplace=True)

In [5]:
df_long[df_long["Similarity"]<1.0].sort_values("Similarity")

                     Similarity
Row       Column
PSPN      CD40L       -0.469981
CD40L     PSPN        -0.469981
IL-1-beta TRAIL       -0.448407
TRAIL     IL-1-beta   -0.448407
EPO       IL-1-beta   -0.444657
...                         ...
IL-7      IL-2         0.858104
IL-2      IL-15        0.906343
IL-15     IL-2         0.906343
IFN-omega IFN-beta     0.968751
IFN-beta  IFN-omega    0.968751

[8010 rows x 1 columns]

In [9]:
df_long.loc["IL-32-beta"].sort_values("Similarity")

            Similarity
Column
TL1A         -0.102120
IL-12        -0.097743
IL-7         -0.073998
TPO          -0.068014
IL-8         -0.058761
...                ...
RANKL         0.208920
IL-17B        0.227576
IL-6          0.240147
IL-10         0.553669
IL-32-beta    1.000001

[90 rows x 1 columns]